name: kryonex_address_picker_example
description: Example app for kryonex_address_picker
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  kryonex_address_picker:
    path: ../

flutter:
  uses-material-design: true
